/* Generated by scripts/gen_family_emoji_assets.py */
#pragma once

#include "lvgl.h"

#define FAMILY_EMOJI_RING_COUNT 9

extern const lv_image_dsc_t *const family_emoji_ring[FAMILY_EMOJI_RING_COUNT];
