#!/usr/bin/env python3
"""
Rasterize ring emoji to LVGL lv_image_dsc_t (ARGB8888, BGRA bytes per lv_color32_t).

Requires: pip install pillow
Default font (macOS): /System/Library/Fonts/Apple Color Emoji.ttc
Override: FAMILY_EMOJI_FONT=/path/to/emoji.ttf

Run from repo root:
  python3 scripts/gen_family_emoji_assets.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Install Pillow: pip install pillow", file=sys.stderr)
    sys.exit(1)

# 8 smileys + ALLA broadcast (megaphone — not a smiley)
EMOJIS = ["😀", "😃", "😄", "😁", "😆", "😊", "🙂", "😇", "📢"]
SIZE = 32
FONT_SIZE = 26

OUT_C = Path(__file__).resolve().parents[1] / "firmware" / "main" / "assets" / "family_emoji_assets.c"
OUT_H = Path(__file__).resolve().parents[1] / "firmware" / "main" / "assets" / "family_emoji_assets.h"


def find_font() -> str:
    env = os.environ.get("FAMILY_EMOJI_FONT")
    if env and os.path.isfile(env):
        return env
    mac = "/System/Library/Fonts/Apple Color Emoji.ttc"
    if os.path.isfile(mac):
        return mac
    # Common Linux paths
    for p in (
        "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf",
        "/usr/share/fonts/noto/NotoColorEmoji.ttf",
    ):
        if os.path.isfile(p):
            return p
    raise FileNotFoundError(
        "No emoji font found. Set FAMILY_EMOJI_FONT to a .ttf/.ttc with color emoji."
    )


def render_char(ch: str, font: ImageFont.FreeTypeFont) -> Image.Image:
    im = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(im)
    bbox = draw.textbbox((0, 0), ch, font=font, embedded_color=True)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = (SIZE - w) // 2 - bbox[0]
    y = (SIZE - h) // 2 - bbox[1]
    draw.text((x, y), ch, font=font, embedded_color=True)
    return im


def rgba_to_lv_bgra_bytes(im: Image.Image) -> bytes:
    """lv_color32_t: blue, green, red, alpha (see lv_color.h)."""
    px = im.convert("RGBA").load()
    out = bytearray()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            out.extend((b, g, r, a))
    return bytes(out)


def main() -> None:
    font_path = find_font()
    font = ImageFont.truetype(font_path, FONT_SIZE)

    OUT_C.parent.mkdir(parents=True, exist_ok=True)

    blocks: list[str] = []
    names: list[str] = []
    for i, ch in enumerate(EMOJIS):
        im = render_char(ch, font)
        data = rgba_to_lv_bgra_bytes(im)
        arr_name = f"family_emoji_ring_{i}_map"
        hex_lines = []
        for j in range(0, len(data), 16):
            chunk = data[j : j + 16]
            hex_lines.append(
                "    " + ", ".join(f"0x{b:02x}" for b in chunk) + ","
            )
        blocks.append(
            f"static const uint8_t {arr_name}[] = {{\n"
            + "\n".join(hex_lines)
            + f"\n}};\n\n"
            f"const lv_image_dsc_t family_emoji_ring_{i} = {{\n"
            f"    .header = {{\n"
            f"        .magic = LV_IMAGE_HEADER_MAGIC,\n"
            f"        .cf = LV_COLOR_FORMAT_ARGB8888,\n"
            f"        .flags = 0,\n"
            f"        .w = {SIZE},\n"
            f"        .h = {SIZE},\n"
            f"        .stride = {SIZE * 4},\n"
            f"        .reserved_2 = 0,\n"
            f"    }},\n"
            f"    .data_size = sizeof({arr_name}),\n"
            f"    .data = {arr_name},\n"
            f"    .reserved = NULL,\n"
            f"}};\n"
        )
        names.append(f"family_emoji_ring_{i}")

    c_src = (
        "/* Generated by scripts/gen_family_emoji_assets.py — do not edit by hand */\n"
        '#include "family_emoji_assets.h"\n'
        '#include "lvgl.h"\n\n'
        + "\n".join(blocks)
        + "\nconst lv_image_dsc_t *const family_emoji_ring[FAMILY_EMOJI_RING_COUNT] = {\n"
    )
    for n in names:
        c_src += f"    &{n},\n"
    c_src += "};\n"

    h_src = (
        "/* Generated by scripts/gen_family_emoji_assets.py */\n"
        "#pragma once\n\n"
        "#include \"lvgl.h\"\n\n"
        "#define FAMILY_EMOJI_RING_COUNT 9\n\n"
        "extern const lv_image_dsc_t *const family_emoji_ring[FAMILY_EMOJI_RING_COUNT];\n"
    )

    OUT_C.write_text(c_src, encoding="utf-8")
    OUT_H.write_text(h_src, encoding="utf-8")
    print(f"Wrote {OUT_C}\nWrote {OUT_H}\nFont: {font_path}")


if __name__ == "__main__":
    main()
